spring:
  application:
    name:  ${APPLICATION_NAME:digi-cms-service}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://103.200.23.126:3306/lambanha_DB-PROD}
    username: ${DATASOURCE_USERNAME:lambanha_admin}
    password: ${DATASOURCE_PASSWORD:Banhmy09@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      validation-timeout: ${DATASOURCE_HIKARI_VALIDATION_TIMEOUT:10000}
      connection-timeout: ${DATASOURCE_HIKARI_CONNECTION_TIMEOUT:10000}
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:10}
      max-lifetime: ${DATASOURCE_HIKARI_MAX_LIFETIME:1800000}
      data-source-properties:
        cacheServerConfiguration: ${DATASOURCE_CACHE_SERVER_CONFIGURATION:true}
        useLocalSessionState: ${DATASOURCE_USE_LOCAL_SESSION_STATE:true}
        cachePrepStmts: ${DATASOURCE_CACHE_PREP_STMTS:true}
        prepStmtCacheSize: ${DATASOURCE_PREP_STMT_CACHE_SIZE:250}
        prepStmtCacheSqlLimit: ${DATASOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
        cacheCallableStmts: ${DATASOURCE_CACHE_CALLABLE_STMTS:true}
        useServerPrepStmts: ${DATASOURCE_USE_SERVER_PREP_STMTS:true}
        rewriteBatchedStatements: ${DATASOURCE_REWRITE_BATCHED_STATEMENTS:true}
        maintainTimeStats: ${DATASOURCE_MAINTAIN_TIME_STATS:false}
        logSlowQueries: ${DATASOURCE_LOG_SLOW_QUERIES:false}
        leakDetectionThreshold: ${$DATASOURCE_LEAK_DETECTION_THRESHOLD:0}
  jpa:
    open-in-view: ${JPA_OPEN_IN_VIEW:true}
    database: mysql
    show-sql: ${JPA_OPEN_IN_VIEW:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: ${HIBERNATE_STATISTICS:true}
        jdbc.batch_size: ${DATASOURCE_BATCH_SIZE:100}
        order_inserts: true
        order_updates: true
        continue-on-error: true
  security:
    2fa:
      enabled: ${GOOGLE_2FA_ENABLE:false}
      secret-key: ${GOOGLE_2FA_SECRET:KEY}
    recaptcha:
      enabled: ${GOOGLE_RECAPTCHA_ENABLE:false}
      url: ${GOOGLE_RECAPTCHA_URL}
      secret-key: ${GOOGLE_RECAPTCHA_SECRET:KEY}
aes-secret: ${AES_SECRET}
file:
  dir: ${FILE_DIR:/data/html/static.dev.wiinvent.tv}
  url: ${FILE_URL:https://static.dev.wiinvent.co}
springdoc:
  api-docs:
    path: /v1/portal/docs/api/index.html
  swagger-ui:
    path: /v1/portal/docs/index.html
    display-request-duration: true
    syntax-highlight:
      activated: true
      theme: monokai
    filter: true
    tags-sorter: alpha
    operations-sorter: alpha
gami:
  service:
    domain: ${GAMI_SERVICE_DOMAIN}
logging:
  level:
    org.springframework.web: ${LOG_LEVEL:debug}
    com.managersystem: ${LOG_LEVEL:debug}
ok:
  http:
    connect-timeout: ${OKHTTP3_CONNECT_TIMEOUT:5}
    read-timeout: ${OKHTTP3_READ_TIMEOUT:8}
    write-timeout: ${OKHTTP3_WRITE_TIMEOUT:8}
    max-idle-connections: ${OKHTTP3_MAX_IDLE_CONNECTIONS:200}
    keep-alive-duration: ${OKHTTP3_KEEP_ALIVE_DURATION:300}
redis:
  prefix-key-vt-game: ${REDIS_PREFIX_KEY_VT_GAME:wiiportal}
  prefix-key: ${REDIS_PREFIX_KEY:mos}
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      base-path: /v1/monitor
      exposure:
        include: health,info,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true