package com.wiinvent.gami.domain.entities.type;

public enum ResourceType {
  SPIN,
  UNBOX,
  BUY_PRODUCT_PACKAGE,
  LEVEL_UP,
  BUY_GVC_PACKAGE,
  CHALLENGE,
  TOURNAMENT,
  MANUAL,
  JACKPOT_REWARD,
  PLACE_JACKPOT,
  BUY_CHARACTER,
  FREE_CHARACTER,
  BUY_CHALLENGE,
  INVITE_FRIEND,
  COMPLETE_ACHIEVEMENT,
  EXCHANGE_PIECE,
  REWARD_COLLECTION
}
