name: Sample Github CD for Bizfly App Engine

on:
  push:
    branches: [ "master" ]  # Sẽ kích hoạt jobs ở dưới khi có sự kiện push lên branch master

jobs:
  deploy:
    runs-on: ubuntu-latest  # Sử dụng runner chạy bằng ubuntu
    steps:
      - name: Trigger deploy in Bizfly App Engine
        run: curl -X POST ${{ secrets.WEB_HOOK_URL }}
